---
title: 'Atomic Vectors'
output: html_document
---

## Atomic Vector Structures

<br>

### Double

```{r}
double <- c(1, 0.1, 1.0, 1.01)
is.double(double)
```

<br> 

### Integer

```{r}
integer <- c(1L, 500L, 0L)
is.integer(integer)
```

<br> 

### logical

```{r}
logical <- c(T, TRUE, F, FALSE)
is.logical(logical)
```

<br>

### Character
```{r}
character <- c('string_1', "string 2", '345')
is.character(character)
```

<br>


## Coercion Rules

<br>

coercion based on which retains the most information.

<br>

### logical to numeric (double or integer)
```{r}
mixed <- c(T, 1L)
typeof(mixed)
```

<br>

### integer to double
```{r}
mixed <- c(1, 2L)
typeof(mixed)
```

<br>

### Everything to character
```{r}
mixed_1 <- c('a', 1)
mixed_2 <- c(T, 'a')
mixed_3 <- c('a', 1L)

typeof(mixed_1)
typeof(mixed_2)
typeof(mixed_3)
```

<br>

## Forcing Coersion

some functions will force coersion on there own, helpful for counting

```{r}
example_log <- c(T, T, F)
example_num <- as.numeric(example_log)

example_num

sum(example_log)
mean(example_log)
```

<br>





